version: '3'
services:
  node_app:
    build: 
      context: ./Node_site
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    
  java-api:
    build:
      context: ./api_spring
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

