services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: tot-postgres:1.0.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - my-network

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - my-network
    depends_on:
      - postgres

  node-web-app:
    build:
      context: ./node_site
      dockerfile: Dockerfile
    image: tot-node-app:1.0.1
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my-network

  java-api-cow-and-bull:
    build:
      context: ./api_spring/cow_and_bull
      dockerfile: Dockerfile
    image: cow-and-bull:1.0.1
    ports:
      - "3030:3030"
    networks:
      - my-network

  java-occasion:
    build:
      context: ./api_spring/occasion
      dockerfile: Dockerfile
    image: occasion:1.0.1
    ports:
      - "3040:3040"
    env_file:
      - .env
    networks:
      - my-network

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
