services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgresql/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - my-network
  
  node_app:
    build: 
      context: ./node_site
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my-network
    
  java-api-cow-and-bull:
    build:
      context: ./api_spring/cow_and_bull
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - my-network
    
  java-occasion:
    build:
      context: ./api_spring/occasion
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
