spring.application.name=Cow_and_Bull
server.port=3030

spring.datasource.url=jdbc:postgresql://localhost:5432/totdatabase
spring.datasource.username=totuser
spring.datasource.password=5471721488
spring.jpa.hibernate.ddl-auto=update